namespace Core.Media.Emoji;

public static class EmojiManager
{
    public static string GetEmoji(EmojiEnum emoji)
    {
        return emoji switch
        {
            #region Faces
            EmojiEnum.LaughingFace1 => "😀",
            EmojiEnum.LaughingFace2 => "😁",
            EmojiEnum.LaughingFace3 => "😆",
            EmojiEnum.LaughingFace4 => "😅",
            EmojiEnum.LaughingFace5 => "😂",
            EmojiEnum.LaughingFace6 => "😄",
            EmojiEnum.LaughingFace7 => "😃",
            EmojiEnum.LaughingFace8 => "🤣",
            EmojiEnum.LaughingFaceWithOneHand1 => "🤭",
            EmojiEnum.SmilingFace1 => "🙂",
            EmojiEnum.SmilingFace2 => "😊",
            EmojiEnum.WinkingFace1 => "😉",
            EmojiEnum.SaintFace1 => "😇",
            EmojiEnum.InvertedFace1 => "🙃",
            EmojiEnum.KissingFace1 => "😚",
            EmojiEnum.KissingFace2 => "😙",
            EmojiEnum.KissingFace3 => "😗",
            EmojiEnum.KissingFace4 => "😘",
            EmojiEnum.HeartEyesFace1 => "😍",
            EmojiEnum.StarEyesFace1 => "🤩",
            EmojiEnum.FaceWithHearts1 => "🥰",
            EmojiEnum.FaceWithTongue1 => "😋",
            EmojiEnum.FaceWithTongue2 => "😛",
            EmojiEnum.WinkingFaceWithTongue1 => "😜",
            EmojiEnum.WinkingFaceWithTongue2 => "😝",
            EmojiEnum.CrazyFaceWithTongue1 => "🤪",
            EmojiEnum.PensiveFace1 => "😐",
            EmojiEnum.FaceWithTwoHands1 => "🤗",
            EmojiEnum.PokerFace1 => "🤗",
            EmojiEnum.WithoutMouthFace1 => "😶",
            EmojiEnum.ShowingTeethFace1 => "😬",
            EmojiEnum.SmugFace1 => "😏",
            EmojiEnum.SuspiciousFace1 => "😑",
            EmojiEnum.DisapprovingFace1 => "😒",
            EmojiEnum.EyeRollingFace1 => "🙄",
            EmojiEnum.RaisedBrowFace1 => "🤨",
            EmojiEnum.CuteFace1 => "😌",
            EmojiEnum.SadFace1 => "😔",
            EmojiEnum.SadFace2 => "😖",
            EmojiEnum.SadFace3 => "😧",
            EmojiEnum.SadFace4 => "😫",
            EmojiEnum.SadFace5 => "😞",
            EmojiEnum.SadFace6 => "😕",
            EmojiEnum.SadFace7 => "😟",
            EmojiEnum.SadFace8 => "😩",
            EmojiEnum.SadFace9 => "🙁",
            EmojiEnum.SadFace10 => "😣",
            EmojiEnum.SadFace11 => "😦",
            EmojiEnum.AngryFace1 => "😡",
            EmojiEnum.AngryFace2 => "😠",
            EmojiEnum.AngryFace3 => "🤬",
            EmojiEnum.DroolingFace1 => "🤤",
            EmojiEnum.SleepingFace1 => "😴",
            EmojiEnum.FaceWithMask1 => "😷",
            EmojiEnum.DeadFace1 => "😵",
            EmojiEnum.ColdFace1 => "🥶",
            EmojiEnum.ExplodingHeadFace1 => "🤯",
            EmojiEnum.NauseaFace1 => "🤢",
            EmojiEnum.VomitingFace1 => "🤮",
            EmojiEnum.FaceWithThermometer1 => "🤒",
            EmojiEnum.FaceWithHolidayCup1 => "🥳",
            EmojiEnum.FaceWithSunglasses1 => "😎",
            EmojiEnum.NerdFaceWithEyeglasses => "🤓",
            EmojiEnum.FaceWithTears1 => "😭",
            EmojiEnum.FaceWithOneTear1 => "😢",
            EmojiEnum.FaceWithBigEyes1 => "🥺",
            #endregion

            #region OtherFaces
            EmojiEnum.Skull1 => "💀",
            EmojiEnum.Devil1 => "👿",
            EmojiEnum.Devil2 => "😈",
            EmojiEnum.Poop1 => "💩",
            EmojiEnum.Alien1 => "👽",
            EmojiEnum.Tetris1 => "👾",
            EmojiEnum.Ghost1 => "👻",
            EmojiEnum.Clown1 => "🤡",
            EmojiEnum.Robot1 => "🤖",
            #endregion

            #region Hearts
            EmojiEnum.Heart1 => "💜",
            EmojiEnum.Heart2 => "💚",
            EmojiEnum.Heart3 => "🤍",
            EmojiEnum.Heart4 => "🤎",
            EmojiEnum.Heart5 => "🧡",
            EmojiEnum.Heart6 => "🖤",
            EmojiEnum.Heart7 => "💙",
            EmojiEnum.Heart8 => "💛",
            EmojiEnum.Heart9 => "💘",
            EmojiEnum.Heart10 => "❤",
            EmojiEnum.Heart11 => "💔",
            EmojiEnum.Heart12 => "💝",
            EmojiEnum.Heart13 => "💕",
            EmojiEnum.Heart14 => "💖",
            #endregion
            _ => string.Empty
        };
    }
}